### PR TITLE
Change counter to uint64_t

### LINKED ISSUE #2: Incorrect digest after 2^32 bits = 512 MB
This implementation uses an internal byte counter of width 32 bits that's additionally shifted by 3 to the left to count bits instead of bytes. The counter overflows after processing  2^32 bits = 512 MB and the library produces wrong digests.

### PR DESCRIPTION
**Pull request by real-or-random**
I hope this fixes #2. I haven't tested this.

### CODE REVIEW

**Comment by markpeek** [comment]
@samrushing can you review, test, and approve?

**Comment by samrushing** [comment]
Sorry for the delay!  The bitcount is obviously being packed as a 64-bit quantity.   Although I found some C implementations using 'int' or 'uint32_t', uint64_t is obviously correct.  That's also what's used in NaCl/libsodium.

**Comment by samrushing** [comment]
Heh, I added an 8GB test and it took 2200s to fail.  You sure you want a test? 8^)

**Comment by markpeek** [comment]
Technically I did get you to test it. ;-) Are you going to hit "Approve" through "[Review Changes](https://github.com/cloudtools/sha256/pull/3/files)"?

**Comment by samrushing** [comment]
```diff
diff --git a/tests/test_sha256.py b/tests/test_sha256.py
index 6290ea3..968f993 100644
--- a/tests/test_sha256.py
+++ b/tests/test_sha256.py
@@ -50,6 +50,14 @@ class TestSHA256(unittest.TestCase):
                     s = new
             self.assertEquals(s.hexdigest(), hash)
 
+    def test_counter(self):
+        s = 'X' * 1048576
+        h0 = sha()
+        h1 = hsha()
+        for i in range (512):
+            h0.update (s)
+            h1.update (s)
+        self.assertEquals (h0.hexdigest(), h1.hexdigest())
 
 if __name__ == '__main__':
     unittest.main()
```

That takes about 150s to run, add it if you dare!

**Review by samrushing — APPROVED** [review]

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
